# Generated by Django 5.2.4 on 2025-10-25 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_is_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staff',
            new_name='Admin',
        ),
    ]
