# Generated by Django 5.1.5 on 2025-07-17 14:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='IATA Code')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('timezone', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Airports',
                'ordering': ['city'],
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_id', models.CharField(max_length=10, unique=True)),
                ('airline', models.CharField(max_length=100)),
                ('flight_number', models.CharField(max_length=10)),
                ('operating_airline', models.CharField(blank=True, max_length=100)),
                ('flight_status', models.CharField(choices=[('scheduled', 'Scheduled'), ('delayed', 'Delayed'), ('departed', 'Departed'), ('arrived', 'Arrived'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('total_seats', models.PositiveSmallIntegerField()),
                ('economy_seats', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('business_seats', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('first_seats', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('economy_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('business_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('first_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrivals', to='flights.airport')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departures', to='flights.airport')),
            ],
            options={
                'ordering': ['departure_time'],
                'indexes': [models.Index(fields=['flight_number'], name='flights_fli_flight__794da4_idx'), models.Index(fields=['departure_airport', 'arrival_airport'], name='flights_fli_departu_4d882b_idx'), models.Index(fields=['departure_time'], name='flights_fli_departu_5bc2af_idx')],
            },
        ),
    ]
